"""add indexes

Revision ID: cf68fb52304f
Revises: b04b6e3ac07a
Create Date: 2025-06-06 08:03:01.634714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf68fb52304f'
down_revision = 'b04b6e3ac07a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_movements_movement_id'), 'movements', ['movement_id'], unique=False)
    op.create_index(op.f('ix_warehouses_product_id'), 'warehouses', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouses_product_id'), table_name='warehouses')
    op.drop_index(op.f('ix_movements_movement_id'), table_name='movements')
    # ### end Alembic commands ###
